# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bbb84ce573dd6e2c4e9c3a31d31b7dc7f2058bfa2d2aa5ae2c78326fd3c2477f87fea86a22b436ea2b5d80165d7da03f8d4b6429b531044d82c19e2b8be9b4d

test:
  secret_key_base: c7f5411e84066f9a26a406e20663d477cef8d8953972ea29f2e25907acc7c520412912051fd35f696f8591f0970ce783f4639886a2ed11952e9a9e45572ec387

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
